FROM arm64v8/node:10.19
# Create app directory
RUN mkdir -p /usr/app
COPY . /usr/app
RUN cd /usr/app/programs/server && npm install --unsafe-perm

WORKDIR /usr/app

ENV PORT='3000'
ENV MONGO_URL='mongodb://10.0.1.40:30017/temperature-logger'
ENV ROOT_URL='http://10.0.1.42/'
CMD [ "node", "main.js" ]
EXPOSE 3000