apiVersion: v1
kind: Service
metadata:
   name: mongo-service-temp-logger
spec:
   type: NodePort
   ports:
      - port: 27010
        targetPort: 27017
        nodePort: 30017
  selector:
    component: mongodb