apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mongo-data-db-temp-logger
spec:
   storageClassName: local
   resources:
      requests:
         storage: 1Gi
   accessModes:
      - ReadWriteOnce
   selector:
      matchLabels:
         app: mongo-temp-logger
